namespace RDPCOMAPILib
{
    public enum ATTENDEE_DISCONNECT_REASON
    {
        ATTENDEE_DISCONNECT_REASON_APP = 0,

        ATTENDEE_DISCONNECT_REASON_MIN = 0,

        ATTENDEE_DISCONNECT_REASON_ERR = 1,

        ATTENDEE_DISCONNECT_REASON_CLI = 2,

        ATTENDEE_DISCONNECT_REASON_MAX = 2,
    }
}