namespace RDPCOMAPILib
{
    public enum RDPENCOMAPI_CONSTANTS
    {
        CONST_ATTENDEE_ID_EVERYONE = -1,

        CONST_ATTENDEE_ID_HOST = 0,

        CONST_MAX_CHANNEL_NAME_LEN = 8,

        CONST_CONN_INTERVAL = 50,

        CONST_MAX_CHANNEL_MESSAGE_SIZE = 1024,

        CONST_MAX_LEGACY_CHANNEL_MESSAGE_SIZE = 409600,
    }
}